/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServicesImport } from './routes/services'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as VendorsIndexImport } from './routes/vendors/index'
import { Route as VendorsVendorIdImport } from './routes/vendors/$vendorId'

// Create/Update Routes

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VendorsIndexRoute = VendorsIndexImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRoute,
} as any)

const VendorsVendorIdRoute = VendorsVendorIdImport.update({
  id: '/vendors/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdImport
      parentRoute: typeof rootRoute
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors': typeof VendorsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors': typeof VendorsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors/': typeof VendorsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/services' | '/vendors/$vendorId' | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/services' | '/vendors/$vendorId' | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/services'
    | '/vendors/$vendorId'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ServicesRoute: typeof ServicesRoute
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ServicesRoute: ServicesRoute,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/services",
        "/vendors/$vendorId",
        "/vendors/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/vendors/$vendorId": {
      "filePath": "vendors/$vendorId.tsx"
    },
    "/vendors/": {
      "filePath": "vendors/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
